server:
  port: 8090
spring:
  application:
    name: ms-gateway-server
  cloud:
    gateway:
      routes:
        - id: ms-product
          uri:
            lb://ms-productos-2023
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2
            - name: EjemploCookie
              args:
                mensaje: Hola mi mensaje personalizado
                cookieValor: ealfriadez
                cookieNombre: usuario
        - id: ms-cart
          uri:
            lb://ms-cart-2024
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=2
#          - AddRequestHeader=token-request, 123456
#          - AddResponseHeader=token-response, 12345678
#          - SetResponseHeader=Content-Type, text/plain
#          - AddRequestParameter=nombre, Jean